print("¡Vamos a ver los tipos de variables en python y tu me vas a ayudar!")
string = input("Empecemos con una variable de tipo string para esto dime tu nombre.")
nt = input("Ahora dime tu edad para conocer una variable de tipo int.")
float =input("Ahora dame tu número favorito, lo dividere entre mi número favorito para que observes una variable tipo float ")
c=int (float)
division = (c/13)
true= ("true")
false=("false")
print("Variable tipo string: ",string)
print("Variale tipo int:" , nt)
print("Variabl tipo float: ",division)
print("Para terminar las variables de tipo booleano pueden ser verdaderas: ", true ," o falsas: ", false )